<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <!-- Required for tests. -->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.PerfectEvent" Version="27.0.5" />
    <PackageReference Include="CK.SVersion" Version="0.2.5" />
    <PackageReference Include="CK.Packaging.Abstractions" Version="0.1.1" />
    <PackageReference Include="CK.CanaryPackage" Version="1.0.0" />
    <PackageReference Include="CK.Monitoring" Version="26.0.5" />
    <PackageReference Include="LibGit2Sharp" Version="0.32.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.12" />
  </ItemGroup>
</Project>