<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NuGet.Credentials" Version="7.3.1" />
        <PackageReference Include="CK.Packaging.Model" Version="0.0.0--ci.5" />
    </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CKli.Build.Plugin\CKli.Build.Plugin.csproj" />
  </ItemGroup>

</Project>